#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

HOMEBREW_PATH="`brew --prefix`"

export RBENV_ROOT="$HOMEBREW_PATH/var/rbenv"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# araxis merge path
if [ -d "/Applications/Araxis Merge.app/Contents/Utilities" ]; then
  export PATH="$PATH:/Applications/Araxis Merge.app/Contents/Utilities"
fi
